title: Learning to fly
author: Bastian
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  That's just a description for google. Nothing special. Just learning lab.

# social links
github_username:  mpiotrowski-im

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
